steps:
- task: Gradle@4
  displayName: 'gradlew build'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Pipeline.Workspace)'
  inputs:
    TargetFolder: '$(Pipeline.Workspace)'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
